# Site
repository: taesikk/taesikk.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 박태식
title: 서버 백엔드 개발자
email: dlwhsktm@naver.com
website: www.github.com/taesikk/taesikk.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: taesikk

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Java & Spring, NodeJS & JavaScript 기반 3년차 서버 백엔드 개발자입니다. Saas 기반의 서비스 개발, 현대, 셀트리온, LG유플러스 등 다양한 온프레미스 프로젝트를 진행해 왔습니다.

  서비스 개발 뿐만 아니라 테스트 또한 중요하다고 생각되어 온프레미스 프로젝트 진행 시 JUnit을 기반으로 한 테스트 코드도 많이 작성하였습니다.
  업무적인 부분 이외에도 지속적인 관심과 자기 계발을 위해 **개인 프로젝트** 및 **팀 프로젝트**를 진행하고 있습니다.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: (주)포시에스
        link: https://www.eformsign.com
        # link_text: boringcompany.com
        sub_title: Java & Spring 백엔드 개발자
        caption: 2023.03 ~ 현재
        quote: >
          전자문서 계약 서비스
        description: | # this will include new lines to allow paragraphs
            - 전자문서 솔루션 개발 및 유지보수
            - 온프레미스 프로젝트 다수 참여하여 개발 및 유지보수
            - open API 및 임베딩 서비스 개발


  - title: 역량 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 이폼사인 서비스 기능 개발
        # link: 
        # link_text: Project Website
        #additional_links:
         # - title:  sproogen/modern-resume-theme
         #   icon: fab fa-github
         #   url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
          
        description: | # this will include new lines to allow paragraphs
          - 템플릿 배포 요청 기능 및 권한 관련 기능 개발
          - RDBMS 테이블 설계 및 비즈니스 로직 개발
          - 템플릿 배포 예정일 비동기 스케줄러 개발
          - JUnit 기반 테스트 코드 작성
      
      - layout: top-middle
        title: 온프레미스 프로젝트 참여
          
        description: | # this will include new lines to allow paragraphs
          - 현대 전사 전자문서 도입 프로젝트에서 임베딩 모듈 개발
          - 현대 국내판매 시스템 프로젝트에서 임베딩 개발 및 open API 개발
          - LG유플러스 사내 인장 동기화 스케줄러 개발
          - NH투자증권 전자 인장 관리 시스템 내 인감 증명서 관리 개발

  - title: Opensource # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: chatforyou
        link: https://github.com/SeJonJ/ChatForYou
        quote: >
          실시간 화상 채팅 및 게임 플랫폼
        description: | # this will include new lines to allow paragraphs
            - 서비스 내 구글 소셜 로그인 도입
            - redis를 활용한 token 관리(토큰 저장, 조회)
            - 회원 관련 mySql 테이블 생성
            - redis와 kafka를 활용한 실시간 친구 요청 및 수락 기능 개발 중
            

  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Backend          
        description: #| this will include new lines to allow paragraphs
            - Java, Spring, Spring MVC, Spring Batch, JPA/Hibernate, Redis
            - mySql, MariaDB, Oracle
            - IntelliJ, Git

      - layout: left
        title: FrontEnd
        description: #| this will include new lines to allow paragraphs
            - HTML, JavaScript
            - Npm, Visual Studio Code
            

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
